// flow-typed signature: b3ec93ffada669e633e53c812b1ca4f1
// flow-typed version: <<STUB>>/bugsnag-react-native_v^2.5.3/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bugsnag-react-native'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bugsnag-react-native' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bugsnag-react-native/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'bugsnag-react-native/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'bugsnag-react-native/lib/Bugsnag' {
  declare module.exports: any;
}

declare module 'bugsnag-react-native/test-harness/__tests__/index.android' {
  declare module.exports: any;
}

declare module 'bugsnag-react-native/test-harness/__tests__/index.ios' {
  declare module.exports: any;
}

declare module 'bugsnag-react-native/test-harness/app/components/list_item' {
  declare module.exports: any;
}

declare module 'bugsnag-react-native/test-harness/app/components/navigation_bar_route_mapper' {
  declare module.exports: any;
}

declare module 'bugsnag-react-native/test-harness/app/components/scenes/crashy' {
  declare module.exports: any;
}

declare module 'bugsnag-react-native/test-harness/app/components/scenes/main' {
  declare module.exports: any;
}

declare module 'bugsnag-react-native/test-harness/app/components/scenes/register' {
  declare module.exports: any;
}

declare module 'bugsnag-react-native/test-harness/app/components/scenes/repos' {
  declare module.exports: any;
}

declare module 'bugsnag-react-native/test-harness/app/index' {
  declare module.exports: any;
}

declare module 'bugsnag-react-native/test-harness/index.android' {
  declare module.exports: any;
}

declare module 'bugsnag-react-native/test-harness/index.ios' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bugsnag-react-native/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'bugsnag-react-native/coverage/lcov-report/prettify'>;
}
declare module 'bugsnag-react-native/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'bugsnag-react-native/coverage/lcov-report/sorter'>;
}
declare module 'bugsnag-react-native/index' {
  declare module.exports: $Exports<'bugsnag-react-native'>;
}
declare module 'bugsnag-react-native/index.js' {
  declare module.exports: $Exports<'bugsnag-react-native'>;
}
declare module 'bugsnag-react-native/lib/Bugsnag.js' {
  declare module.exports: $Exports<'bugsnag-react-native/lib/Bugsnag'>;
}
declare module 'bugsnag-react-native/test-harness/__tests__/index.android.js' {
  declare module.exports: $Exports<'bugsnag-react-native/test-harness/__tests__/index.android'>;
}
declare module 'bugsnag-react-native/test-harness/__tests__/index.ios.js' {
  declare module.exports: $Exports<'bugsnag-react-native/test-harness/__tests__/index.ios'>;
}
declare module 'bugsnag-react-native/test-harness/app/components/list_item.js' {
  declare module.exports: $Exports<'bugsnag-react-native/test-harness/app/components/list_item'>;
}
declare module 'bugsnag-react-native/test-harness/app/components/navigation_bar_route_mapper.js' {
  declare module.exports: $Exports<'bugsnag-react-native/test-harness/app/components/navigation_bar_route_mapper'>;
}
declare module 'bugsnag-react-native/test-harness/app/components/scenes/crashy.js' {
  declare module.exports: $Exports<'bugsnag-react-native/test-harness/app/components/scenes/crashy'>;
}
declare module 'bugsnag-react-native/test-harness/app/components/scenes/main.js' {
  declare module.exports: $Exports<'bugsnag-react-native/test-harness/app/components/scenes/main'>;
}
declare module 'bugsnag-react-native/test-harness/app/components/scenes/register.js' {
  declare module.exports: $Exports<'bugsnag-react-native/test-harness/app/components/scenes/register'>;
}
declare module 'bugsnag-react-native/test-harness/app/components/scenes/repos.js' {
  declare module.exports: $Exports<'bugsnag-react-native/test-harness/app/components/scenes/repos'>;
}
declare module 'bugsnag-react-native/test-harness/app/index.js' {
  declare module.exports: $Exports<'bugsnag-react-native/test-harness/app/index'>;
}
declare module 'bugsnag-react-native/test-harness/index.android.js' {
  declare module.exports: $Exports<'bugsnag-react-native/test-harness/index.android'>;
}
declare module 'bugsnag-react-native/test-harness/index.ios.js' {
  declare module.exports: $Exports<'bugsnag-react-native/test-harness/index.ios'>;
}
