// flow-typed signature: 8726cb4f9ea3fab283d5d2d6579c8549
// flow-typed version: <<STUB>>/json-api-normalizer_v^0.4.5/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'json-api-normalizer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'json-api-normalizer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'json-api-normalizer/dist/bundle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'json-api-normalizer/dist/bundle.js' {
  declare module.exports: $Exports<'json-api-normalizer/dist/bundle'>;
}
