// flow-typed signature: fb59ab04ee890be9ed5e1c09cb29901f
// flow-typed version: <<STUB>>/plist_v^2.1.0/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'plist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'plist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'plist/dist/plist-build' {
  declare module.exports: any;
}

declare module 'plist/dist/plist-parse' {
  declare module.exports: any;
}

declare module 'plist/dist/plist' {
  declare module.exports: any;
}

declare module 'plist/lib/build' {
  declare module.exports: any;
}

declare module 'plist/lib/parse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'plist/dist/plist-build.js' {
  declare module.exports: $Exports<'plist/dist/plist-build'>;
}
declare module 'plist/dist/plist-parse.js' {
  declare module.exports: $Exports<'plist/dist/plist-parse'>;
}
declare module 'plist/dist/plist.js' {
  declare module.exports: $Exports<'plist/dist/plist'>;
}
declare module 'plist/index' {
  declare module.exports: $Exports<'plist'>;
}
declare module 'plist/index.js' {
  declare module.exports: $Exports<'plist'>;
}
declare module 'plist/lib/build.js' {
  declare module.exports: $Exports<'plist/lib/build'>;
}
declare module 'plist/lib/parse.js' {
  declare module.exports: $Exports<'plist/lib/parse'>;
}
