// flow-typed signature: 7b4b00d49d512acad17b86ba72333e15
// flow-typed version: <<STUB>>/react-native-fetch-polyfill_v^1.1.2/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-fetch-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-fetch-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-fetch-polyfill/fetch-polyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-fetch-polyfill/fetch-polyfill.js' {
  declare module.exports: $Exports<'react-native-fetch-polyfill/fetch-polyfill'>;
}
