// flow-typed signature: 1170542b69f6a2873804dd0b5e99ad0c
// flow-typed version: <<STUB>>/react-native-swipeout_v^2.2.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-swipeout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-swipeout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-swipeout/NativeButton' {
  declare module.exports: any;
}

declare module 'react-native-swipeout/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-swipeout/NativeButton.js' {
  declare module.exports: $Exports<'react-native-swipeout/NativeButton'>;
}
declare module 'react-native-swipeout/index' {
  declare module.exports: $Exports<'react-native-swipeout'>;
}
declare module 'react-native-swipeout/index.js' {
  declare module.exports: $Exports<'react-native-swipeout'>;
}
declare module 'react-native-swipeout/styles.js' {
  declare module.exports: $Exports<'react-native-swipeout/styles'>;
}
