// flow-typed signature: 32c6b4f2264f1f4f3e095cae1dea8d8c
// flow-typed version: <<STUB>>/react-native-action-button_v^2.8.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-action-button'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-action-button' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-action-button/ActionButton' {
  declare module.exports: any;
}

declare module 'react-native-action-button/ActionButtonItem' {
  declare module.exports: any;
}

declare module 'react-native-action-button/example/Basic/index.android' {
  declare module.exports: any;
}

declare module 'react-native-action-button/example/Basic/index.ios' {
  declare module.exports: any;
}

declare module 'react-native-action-button/shared' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-action-button/ActionButton.js' {
  declare module.exports: $Exports<'react-native-action-button/ActionButton'>;
}
declare module 'react-native-action-button/ActionButtonItem.js' {
  declare module.exports: $Exports<'react-native-action-button/ActionButtonItem'>;
}
declare module 'react-native-action-button/example/Basic/index.android.js' {
  declare module.exports: $Exports<'react-native-action-button/example/Basic/index.android'>;
}
declare module 'react-native-action-button/example/Basic/index.ios.js' {
  declare module.exports: $Exports<'react-native-action-button/example/Basic/index.ios'>;
}
declare module 'react-native-action-button/shared.js' {
  declare module.exports: $Exports<'react-native-action-button/shared'>;
}
