// flow-typed signature: 1b1e3b16350b0db5e2dc05c3154f8f9c
// flow-typed version: <<STUB>>/react-native-snackbar_v^0.4.3/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-snackbar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-snackbar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-snackbar/lib/index' {
  declare module.exports: any;
}

declare module 'react-native-snackbar/src/__tests__/index.test' {
  declare module.exports: any;
}

declare module 'react-native-snackbar/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-snackbar/lib/index.js' {
  declare module.exports: $Exports<'react-native-snackbar/lib/index'>;
}
declare module 'react-native-snackbar/src/__tests__/index.test.js' {
  declare module.exports: $Exports<'react-native-snackbar/src/__tests__/index.test'>;
}
declare module 'react-native-snackbar/src/index.js' {
  declare module.exports: $Exports<'react-native-snackbar/src/index'>;
}
