// flow-typed signature: 1455deb82d9d43d793c78b01d2d61fd0
// flow-typed version: <<STUB>>/react-native-swipeout_v^2.3.1/flow_v0.57.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-native-swipeout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-native-swipeout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-native-swipeout/dist/index' {
  declare module.exports: any;
}

declare module 'react-native-swipeout/dist/NativeButton' {
  declare module.exports: any;
}

declare module 'react-native-swipeout/dist/styles' {
  declare module.exports: any;
}

declare module 'react-native-swipeout/src/index' {
  declare module.exports: any;
}

declare module 'react-native-swipeout/src/NativeButton' {
  declare module.exports: any;
}

declare module 'react-native-swipeout/src/styles' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-native-swipeout/dist/index.js' {
  declare module.exports: $Exports<'react-native-swipeout/dist/index'>;
}
declare module 'react-native-swipeout/dist/NativeButton.js' {
  declare module.exports: $Exports<'react-native-swipeout/dist/NativeButton'>;
}
declare module 'react-native-swipeout/dist/styles.js' {
  declare module.exports: $Exports<'react-native-swipeout/dist/styles'>;
}
declare module 'react-native-swipeout/src/index.js' {
  declare module.exports: $Exports<'react-native-swipeout/src/index'>;
}
declare module 'react-native-swipeout/src/NativeButton.js' {
  declare module.exports: $Exports<'react-native-swipeout/src/NativeButton'>;
}
declare module 'react-native-swipeout/src/styles.js' {
  declare module.exports: $Exports<'react-native-swipeout/src/styles'>;
}
