// flow-typed signature: f38def77cf0377e511adec2debc18e3f
// flow-typed version: <<STUB>>/redux-object_v^0.5.2/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-object'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-object' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-object/dist/bundle' {
  declare module.exports: any;
}

declare module 'redux-object/dist/bundle.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-object/dist/bundle.js' {
  declare module.exports: $Exports<'redux-object/dist/bundle'>;
}
declare module 'redux-object/dist/bundle.min.js' {
  declare module.exports: $Exports<'redux-object/dist/bundle.min'>;
}
