// flow-typed signature: 226d873609a4bb465051b0d761e694e9
// flow-typed version: <<STUB>>/xcode_v^0.9.3/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'xcode'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'xcode' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'xcode/lib/parseJob' {
  declare module.exports: any;
}

declare module 'xcode/lib/parser/pbxproj' {
  declare module.exports: any;
}

declare module 'xcode/lib/pbxFile' {
  declare module.exports: any;
}

declare module 'xcode/lib/pbxProject' {
  declare module.exports: any;
}

declare module 'xcode/lib/pbxWriter' {
  declare module.exports: any;
}

// Filename aliases
declare module 'xcode/index' {
  declare module.exports: $Exports<'xcode'>;
}
declare module 'xcode/index.js' {
  declare module.exports: $Exports<'xcode'>;
}
declare module 'xcode/lib/parseJob.js' {
  declare module.exports: $Exports<'xcode/lib/parseJob'>;
}
declare module 'xcode/lib/parser/pbxproj.js' {
  declare module.exports: $Exports<'xcode/lib/parser/pbxproj'>;
}
declare module 'xcode/lib/pbxFile.js' {
  declare module.exports: $Exports<'xcode/lib/pbxFile'>;
}
declare module 'xcode/lib/pbxProject.js' {
  declare module.exports: $Exports<'xcode/lib/pbxProject'>;
}
declare module 'xcode/lib/pbxWriter.js' {
  declare module.exports: $Exports<'xcode/lib/pbxWriter'>;
}
