# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'goodshmob' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!


  # Pods for goodshmob
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTAnimation',
    #'RCTAdSupport',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
]
  

  # pod 'RNDeviceInfo', path: '../node_modules/react-native-device-info'

  

  target 'goodshmobTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        
        
        #https://github.com/facebook/react-native/issues/12814
        if target.name == "React"
            target.remove_from_project
        end
        
        if target.name == 'react-native-config'
            phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
            phase.shell_script = "cd ../../"\
            " && RNC_ROOT=./node_modules/react-native-config/"\
            " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
            " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
            " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
            
            target.build_phases << phase
            target.build_phases.move(phase,0)
        end
    end
end
