# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'


target 'goodshmob' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  rn_maps_path = '../node_modules/react-native-maps'

  # Pods for goodshmob
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Firebase/DynamicLinks'
  pod 'react-native-config', :path => '../node_modules/react-native-config'
  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'GoogleMaps'  # Remove this line if you don't want to support GoogleMaps on iOS
  pod 'Google-Maps-iOS-Utils' # Remove this line if you don't want to support GoogleMaps on iOS

  #https://github.com/evollu/react-native-fcm/issues/769
  pod 'nanopb', podspec: 'https://raw.githubusercontent.com/tnantoka/nanopb-podspec/deployment-target/nanopb/0.3.8/nanopb.podspec'


  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    # 'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    'ART',
    'RCTActionSheet',
    'RCTAnimation',
    #'RCTAdSupport',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTPushNotification',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'RCTLinkingIOS'
]
  

  # pod 'RNDeviceInfo', path: '../node_modules/react-native-device-info'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

end

post_install do |installer|
  
  installer.pods_project.targets.each do |target|
    #https://github.com/facebook/react-native/issues/12814
    if target.name == 'react-native-google-maps'
       target.build_configurations.each do |config|
          config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
       end
    end
    if target.name == "React"
       target.remove_from_project
    end

    if target.name == 'react-native-config' then
      phase = target.new_shell_script_build_phase("Build env file")
      phase.shell_script = "cd ../../node_modules/react-native-config/"\
                           " && export SYMROOT=./ios/ReactNativeConfig"\
                           " && export BUILD_DIR=./ios/ReactNativeConfig"\
                           " && ruby ./ios/ReactNativeConfig/BuildDotenvConfig.ruby"

      phase.shell_script = "cd ../../"\
                           " && RNC_ROOT=./node_modules/react-native-config/"\
                           " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
                           " && export BUILD_DIR=$RNC_ROOT/ios/ReactNativeConfig"\
                           " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"

      target.build_phases.move(phase,0)
    end
  end
end
